### ISSUE TITLE
Branch Cleanup

### ISSUE THREAD

**Issue by apazzolini** [BroadleafCommerce/LegacyDemoSite#12]
Let's clean up DemoSite branches too! @bpolster @phillipuniverse @jefffischer @priyeshgpatel @Jerry77oz 

Branches in question:
- CustomerGroups
- i18n
- offer_customization
- price-splits

If you need any of these, please speak up

**Comment by phillipuniverse** [comment]
Anybody have any comments on these branches? Anyone? Bueller?

**Comment by phillipuniverse** [comment]
Backed up these branches locally and deleted them from GitHub. Let me know if anybody needs these pushed back up.
