### ISSUE TITLE
Google Analytics stopped working

### ISSUE THREAD

**Issue by watermelonjuice** [BroadleafCommerce/LegacyDemoSite#122]
The Google Analytics code is being added correctly in the following commits:
(3.0.10-GA) 846fb67d85f0db5f07ffca3d0ebbe7e2a54c13b0
(3.1.0-GA) 0967cc51c1d58d494a558da39e468b40c34cf56a

The Google Analytics code stops being added in DemoSite in these commits
(3.1.1-GA) e5ba32479df7b1a9eaec1332d3160fbc0bf0d1ea
(3.1.2-GA) ae792b8d7c83062a5610900653226fe4884d74af

**Comment by watermelonjuice** [comment]
Works in 3.1.3-SNAPSHOT

**Comment by phillipuniverse** [comment]
By the way @watermelonjuice, I deprecated that processor in favor of the GoogleUniversalAnalyticsProcessor. It contains the things that you suggested in BroadleafCommerce/BroadleafCommerce#572

**Comment by watermelonjuice** [comment]
Thanks! Great work.
