### ISSUE TITLE
Error after switching to my sql

### ISSUE THREAD

**Issue by HatemElSum** [BroadleafCommerce/LegacyDemoSite#130]
After Changing to My SQL
and after starting the server , the Home Page didn't work
and keeps this error

[artifact:mvn] [ WARN] 10:26:19 PageNotFound - No mapping found for HTTP request with URI [/] in DispatcherServlet with name 'heatclinic'
[artifact:mvn] [ WARN] 10:38:13 PageNotFound - No mapping found for HTTP request with URI [/] in DispatcherServlet with name 'heatclinic'

**Comment by letshan** [comment]
Hi HatimAISum,

Have you checked the database? usually this error means you don't have any record in blc_category. Thus you may want to check the data importing.

Keep in mind that the demosite mapping the pages url in the category rather than in spring configuration.

Hope this can help.

Cheers,

Dan

**Comment by winnerawan** [comment]
same problem here on bl 5.x.x but admin page run fine, site page contactus give me 500 error code "HTTP Status 500 - Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "session.blLocale.localeCode" (layout/partials/header:59)" and No mapping found for HTTP request with URI [/]

**Comment by DivyaKMenon** [comment]
same problem here on hitting localhost:8080. Admin url works fine but site page gives error response

HTTP Status 500 - Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "'locale-' + session.blLocale.localeCode" (layout/fullPageLayout:12)

@winnerawan , @HatemAlSum  Any info on how you fixed it?

**Comment by HatemElSum** [comment]
Actually , I switched to another solution

**Comment by danielcolgrove** [comment]
@DivyaKMenon Which version are you running?

**Comment by DivyaKMenon** [comment]
@danielcolgrove  version is 5.1.2-GA
