### ISSUE TITLE
file not found page

### ISSUE THREAD

**Issue by prabhatkataria** [BroadleafCommerce/LegacyDemoSite#132]
Just thinking about how would it be to add a file not found page or error 404 page to demosite as in current setup it does not have one.

I tried to do this using following code in web.xml
...
< error-page >
   < error-cod e>404</ error-code >
   < location >/test</ location >
</ error-page > 
...

but i faced an exception as below
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.broadleafcommerce.core.catalog.domain.CategoryImpl.allChildCategoryXrefs, could not initialize proxy - no Session

**Comment by phillipuniverse** [comment]
Sorry for the late response on this; the problem here is that servlet filters are not executed by default for ERROR pages. Specifically, the openEntityManagerInViewFilter is not executed and thus there is no active Hibernate session on the view layer.

**Comment by prabhatkataria** [comment]
Hi Phillip, you had clearly mentioned reason of exception on BLC forum (http://forum.broadleafcommerce.org/viewtopic.php?f=15&t=3116) so no need for apologies ;).

But I do want to confirm the correct way of handling global exception. Which one of the below according to you is appropriate way?
1. using <error-page> in web.xml, or
2. having ControllerAdvice coupled with ExceptionHandler in one of the classes to catch different exceptions
