### ISSUE TITLE
build failure due to missing property value "product.site.map.generator.row.limit"

### ISSUE THREAD

**Issue by DeanWade** [BroadleafCommerce/LegacyDemoSite#149]
the master branch depends on 3.1.8-GA\broadleaf-framework-3.1.8-GA.jar, which don't contains the property value for "product.site.map.generator.row.limit", and the build on master will always fail.

**Comment by bpolster** [comment]
@DeanWade, The mentioned property is in the jar's _/config/bc/fw/common.properties_ file.

**Comment by bpolster** [comment]
Just to test, ran these steps locally ... 

```
git clone git@github.com:BroadleafCommerce/DemoSite
mvn install
ant jetty-demo
```

After this, you should be able to hit localhost:8080 to see the site running with HSQL and Jetty. 

To get this to work requires the following ...
1.  Must have ant and maven installed
2.  Update the build.properties file to point to the location of your MAVEN home directory.
