### ISSUE TITLE
Ant script does not working

### ISSUE THREAD

**Issue by gconcon** [BroadleafCommerce/LegacyDemoSite#15]
When executing change-identifier target, the following error occurs:
BUILD FAILED
/home/gconcon/workspace/broadleaf/DemoSite/build.xml:49: Warning: Could not find file /home/gconcon/workspace/broadleaf/DemoSite/admin/src/main/resources/com/mycompany/gwt/mycompanyAdmin.gwt.xml to copy.

These files copied by ant don`t exists.

**Comment by munnja001** [comment]
This is fixed by this pull request https://github.com/BroadleafCommerce/DemoSite/pull/17

**Comment by phillipuniverse** [comment]
Thanks @munnja001. Closing this issue as further discussion should be made at #17.
