### ISSUE TITLE
Unrecognized SSL message, plaintext connection? on Jenkins

### ISSUE THREAD

**Issue by snjaga** [BroadleafCommerce/LegacyDemoSite#156]
We were building a Maven project using Broadleaf Demosite Github reposirtoy, it was building fine and we were facing issues only on deploying it on a slave until 30th Dec 2014.

After that we started receiving the below error.

"Caused by: hudson.plugins.git.GitException: Unrecognized SSL message, plaintext connection?"

Please let us know when and how to change the SSL RSA keys? It will be helpful for us to proceed further.

Started by user Administrator
[EnvInject] - Loading node environment variables.
Building remotely on 10.154.34.157 in workspace /home/pesdev/myprojects/workspace/Broadleaf

> git rev-parse --is-inside-work-tree # timeout=10
> Fetching changes from the remote Git repository
> git config remote.origin.url https://github.com/BroadleafCommerce/DemoSite # timeout=10
> Fetching upstream changes from https://github.com/BroadleafCommerce/DemoSite
> git --version # timeout=10
> FATAL: Failed to fetch from https://github.com/BroadleafCommerce/DemoSite
> hudson.plugins.git.GitException: Failed to fetch from https://github.com/BroadleafCommerce/DemoSite
>     at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:627)
>     at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:865)
>     at hudson.plugins.git.GitSCM.checkout(GitSCM.java:890)
>     at hudson.model.AbstractProject.checkout(AbstractProject.java:1252)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:624)
>     at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:530)
>     at hudson.model.Run.execute(Run.java:1732)
>     at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:529)
>     at hudson.model.ResourceController.execute(ResourceController.java:88)
>     at hudson.model.Executor.run(Executor.java:234)
> Caused by: hudson.plugins.git.GitException: Unrecognized SSL message, plaintext connection?
>     at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.checkCredentials(CliGitAPIImpl.java:2198)
>     at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1152)
>     at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$200(CliGitAPIImpl.java:87)
>     at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:266)
>     at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
>     at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
>     at hudson.remoting.UserRequest.perform(UserRequest.java:118)
>     at hudson.remoting.UserRequest.perform(UserRequest.java:48)
>     at hudson.remoting.Request$2.run(Request.java:328)
>     at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:262)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>     at java.lang.Thread.run(Thread.java:745)

**Comment by phillipuniverse** [comment]
I don't know the answer to this one. Something to do with GitHub I suppose?

Closing since there isn't anything that we can do about this.
