### ISSUE TITLE
Jetty. Template resolution error.

### ISSUE THREAD

**Issue by vkolodrevskiy** [BroadleafCommerce/LegacyDemoSite#161]
When I launch mycompany.war on Jetty 9 and opening home page I'm getting following error:

```
HTTP ERROR 500

Problem accessing /. Reason:

    Server Error
Caused by:

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template "/layout/partials/head", template might not exist or might not be accessible by any of the configured Template Resolvers (layout/home:7)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:965)
```

**Comment by phillipuniverse** [comment]
You have to change the templates themselves for Jetty 9, see #157 and #158

That said, we're working on moving to embedded Tomcat in #160.

**Comment by vkolodrevskiy** [comment]
@phillipuniverse,
Is there a difference of how templates are resolved by Jetty and Tomcat? Can that be fixed with some tricky template resolver configuration?

**Comment by phillipuniverse** [comment]
Sorry, I linked the wrong issue in my comment above, it should be #157.

The difference is that there is a problem if you reference absolute paths in the templates, which we were doing. I am going to bet that you don't have to reference templates by absolute path in Tomcat, which means that would be the most cross-compatible way. To see what I mean, look at the commit diffs in #157 like at https://github.com/BroadleafCommerce/DemoSite/pull/157/files#diff-5c801653978e20dd8538e48dd84c3de0L7.

**Comment by vkolodrevskiy** [comment]
@phillipuniverse,
Understood, thanks a lot!
