### ISSUE TITLE
Cant start admin and site for the same reason in tomcat7

### ISSUE THREAD

**Issue by jammyjaccy** [BroadleafCommerce/LegacyDemoSite#162]
MergePersistenceUnitManager - A BroadleafClassTransformer is configured for this persistence unit, but Spring reported a problem (likely that a LoadTimeWeaver is not registered). As a result, the Broadleaf Commerce ClassTransformer (org.broadleafcommerce.common.extensibility.jpa.copy.DirectCopyClassTransformer) is not being registered with the persistence unit.
[ WARN] 12:28:22 MergePersistenceUnitManager - A BroadleafClassTransformer is configured for this persistence unit, but Spring reported a problem (likely that a LoadTimeWeaver is not registered). As a result, the Broadleaf Commerce ClassTransformer (org.broadleafcommerce.common.extensibility.jpa.convert.EntityMarkerClassTransformer) is not being registered with the persistence

can anyone help me?

**Comment by jammyjaccy** [comment]
problem fixed

**Comment by bpolster** [comment]
@jammyjaccy Do you have any context on what was done to fix the problem in case someone else runs into the same problem?

**Comment by benoyprakash** [comment]
Even i am having the same issue, it will be great, if you can give some explanations on how the fix was done.
