### ISSUE TITLE
Encountering Bean creation exception when running tomcat target from site on Demo Site 4.0

### ISSUE THREAD

**Issue by bmulpuri** [BroadleafCommerce/LegacyDemoSite#163]
I am following the getting started with broadleaf 4.0 instructions (http://www.broadleafcommerce.com/docs/c ... ng-started) to setup my site. I am encountering bean creation exceptions when running the tomcat target from site project. This is because it is not able to find the jdbc context. I am assuming it is not able to find the properties defined. Here is the exception stack trace.

[artifact:mvn] [ WARN] 09:06:00 DefaultListableBeanFactory - Bean creation exception on FactoryBean type check: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webDS': Invocation of init method failed; nested exception is javax.naming.NameNotFoundException: Name [jdbc/web] is not bound in this Context. Unable to find [jdbc].

**Comment by phillipuniverse** [comment]
Thanks for the issue report. Just to confirm, what OS are you on? Windows, OSX or Linux?

**Comment by bmulpuri** [comment]
This is on OSX.

Thanks,
Bhaskar

On Thu, Apr 23, 2015 at 2:37 PM, Phillip Verheyden <notifications@github.com

**Comment by ncrum** [comment]
@bmulpuri, I am trying to recreate this issue. 

Here are my steps to set up DemoSite:
1) Clone `DemoSite` repo
2) Open up `DemoSite/build.properties` and set proper path for `maven.home`
3) Run `mvn clean install` within `DemoSite/`
4) Navigate to `DemoSite/site/` and run `ant tomcat`

I just want to verify if these were the steps you followed. These are all done within the command line and not in eclipse. In fact, I would completely exit Eclipse before doing so. Let me know what happens!

> Note: If you were doing this all within eclipse, this issue could be an eclipse problem

**Comment by bmulpuri** [comment]
I am trying this from eclipse following the Getting started guide. I
thought the whole purpose of the Getting started guide and the Eclipse
workspace provided is to allow these to be done from Eclipse.

I will try from command line, but could you try to reproduce from Eclipse.

Thanks,
Bhaskar

**Comment by ncrum** [comment]
@bmulpuri thanks for the suggestion, I went ahead and followed the guide explicitly at (http://www.broadleafcommerce.com/docs/core/4.0/getting-started) for eclipse.

Unfortunately, I was unable to recreate the issue when going through eclipse either. It works on my end.
Could you post the full stack trace from the console?

Thanks

**Comment by bmulpuri** [comment]
Here are the some of the messages from the console.

[artifact:mvn] INFO: Set web app root system property: 'site.root' =
[/Users/bmulpuri/dvlp/tradeleaves/eclipse-workspace/DemoSite/site/src/main/webapp/]

[artifact:mvn] Apr 24, 2015 3:20:54 PM
org.apache.catalina.core.ApplicationContext log

[artifact:mvn] INFO: Initializing log4j from
[/Users/bmulpuri/dvlp/tradeleaves/eclipse-workspace/DemoSite/site/src/main/webapp/WEB-INF/log4j.xml]

[artifact:mvn] Apr 24, 2015 3:20:54 PM
org.apache.catalina.core.ApplicationContext log

[artifact:mvn] INFO: Initializing Spring root WebApplicationContext

[artifact:mvn] [ WARN] 15:21:01 DefaultListableBeanFactory - Bean creation
exception on FactoryBean type check:
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'webDS': Invocation of init method failed; nested exception
is javax.naming.NameNotFoundException: Name [jdbc/web] is not bound in this
Context. Unable to find [jdbc].

[artifact:mvn] [ WARN] 15:21:01 DefaultListableBeanFactory - Bean creation
exception on FactoryBean type check:
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'webSecureDS': Invocation of init method failed; nested
exception is javax.naming.NameNotFoundException: Name [jdbc/secure] is not
bound in this Context. Unable to find [jdbc].

[artifact:mvn] [ WARN] 15:21:01 DefaultListableBeanFactory - Bean creation
exception on FactoryBean type check:
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'webStorageDS': Invocation of init method failed; nested
exception is javax.naming.NameNotFoundException: Name [jdbc/storage] is not
bound in this Context. Unable to find [jdbc].

[artifact:mvn] [ WARN] 15:21:02 MergeXmlWebApplicationContext - Exception
encountered during context initialization - cancelling refresh attempt

[artifact:mvn] org.springframework.beans.factory.BeanCreationException:
Error creating bean with name 'entityManagerFactory' defined in resource
loaded from byte array: Cannot resolve reference to bean
'blPersistenceUnitManager' while setting bean property
'persistenceUnitManager'; nested exception is
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'blPersistenceUnitManager': Injection of resource
dependencies failed; nested exception is
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'blMergedDataSources' defined in resource loaded from byte
array: Cannot resolve reference to bean 'webDS' while setting bean property
'sourceMap' with key [TypedStringValue: value [jdbc/web], target type
[null]]; nested exception is
org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'webDS': Invocation of init method failed; nested exception
is javax.naming.NameNotFoundException: Name [jdbc/web] is not bound in this
Context. Unable to find [jdbc].

Thanks,

Bhaskar

**Comment by ncrum** [comment]
@bmulpuri does it have this at the top:

```
Buildfile: /Users/ncrum/Temp BLC/eclipse-workspace 2/DemoSite/site/build.xml
start-db:
     [echo] Starting Data Base...
tomcat:
[artifact:mvn] Listening for transport dt_socket at address: 8000Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[artifact:mvn] objc[39246]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
[artifact:mvn] [INFO] S
```

**Comment by ncrum** [comment]
Also could you post your build.properties file contents?

My `build.properties`:

```
########
#The following file is used to define runtime properties that will read by ant tasks. 
#if you need to override any of them,
#then create a file in your home directory called .build.properties that contains only the override properties.
#########

#required
maven.home=/usr/local/Cellar/maven/3.2.5/libexec

#optional, used in tomcat-jrebel tasks. This should point to the JRebel 6 agent.

# Windows, 32/64
# jrebel.path=C:/path/to/jrebel/lib/jrebel64.dll
#
# Linux, 32/64
# jrebel.path=/usr/lib/jrebel/lib/libjrebel64.so
#
# OSX, 32/64
# jrebel.path=/usr/lib/jrebel/lib/libjrebel64.dylib

jrebel.path=/Users/ncrum/jrebel/jrebel.jar

#Required for correct operation of some 3rd party modules
#Relative paths are from the ant build.xml files, so site/build.xml and admin/build.xml.
spring.instrument.path=../lib/spring-instrument-4.1.6.RELEASE.jar

# Connection properties for the database given to Tomcat in build.xml and used by META-INF/context.xml
database.user=sa
database.password=
database.driver=org.hsqldb.jdbcDriver
database.url=jdbc:hsqldb:hsql://localhost/broadleaf
```

**Comment by bmulpuri** [comment]
Here is the top part of the log. It is similar to your output. I have also
attached the build.properties file.

What is the ant version you are using? I am currently using the one that is
embedded within eclipse. I am using eclipse STS 3.6.2 (Spring tool suite)
and the embedded ant version is 1.9.2.

Buildfile:
/Users/bmulpuri/dvlp/tradeleaves/eclipse-workspace/DemoSite/site/build.xml

start-db:

```
 [echo] Starting Data Base...
```

tomcat:

```
 [echo] MAVEN_HOME=/Users/bmulpuri/dvlp/apps/apache-maven-3.2.5

 [echo] USER_HOME=/Users/bmulpuri

 [echo] USER_NAME=bmulpuri

 [echo] PROJECT_NAME=site
```

[artifact:mvn] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option
MaxPermSize=256M; support was removed in 8.0

[artifact:mvn] objc[11769]: Class JavaLaunchHelper is implemented in both
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java
and
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/libinstrument.dylib.
One of the two will be used. Which one is undefined.

[artifact:mvn] Listening for transport dt_socket at address: 8000

[artifact:mvn] [INFO] Scanning for projects...

[artifact:mvn] [INFO]

Thanks,

Bhaskar

**Comment by ncrum** [comment]
Hmm, that should be right. Let me try a few more things to try to reproduce it. Have you tried doing it in command line?

**Comment by ncrum** [comment]
Wait, also try updated spring to the newest version. I think its 4.4

**Comment by bmulpuri** [comment]
What is the ant version you are using?

Thanks,
Bhaskar

**Comment by ncrum** [comment]
@bmulpuri Sorry I was away for a while. Here is my ant version: Apache Ant(TM) version 1.9.4.

**Comment by ncrum** [comment]
Also here is my mvn/java versioning:

```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T11:29:23-06:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.7.0_71, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"
```

**Comment by bmulpuri** [comment]
I was able to resolve the issue. I am able to build now from the command
line and from eclipse STS. The problem might have been with the embedded
maven version, 3.2.1, with eclipse STS. Setting the maven version to 3.2.5
is working without any issues. I also tried maven version 3.3.1 but was
running into an issue related to setting M2_HOME environment variable.

I have a question about a different error message I am seeing now during
startup.

[artifact:mvn] [ERROR] 18:00:09 SchemaExport - HHH000389: Unsuccessful:
alter table BLC_ADDITIONAL_OFFER_INFO drop constraint FK3BFDBD63B5D9C34D

[artifact:mvn] [ERROR] 18:00:09 SchemaExport - user lacks privilege or
object not found: PUBLIC.BLC_ADDITIONAL_OFFER_INFO

[artifact:mvn] [ERROR] 18:00:09 SchemaExport - HHH000389: Unsuccessful:
alter table BLC_ADDITIONAL_OFFER_INFO drop constraint FK3BFDBD63D5F3FAF4

[artifact:mvn] [ERROR] 18:00:09 SchemaExport - user lacks privilege or
object not found: PUBLIC.BLC_ADDITIONAL_OFFER_INFO

[artifact:mvn] [ERROR] 18:00:09 SchemaExport - HHH000389: Unsuccessful:
alter table BLC_ADDITIONAL_OFFER_INFO drop constraint FK3BFDBD631891FF79

[artifact:mvn] [ERROR] 18:00:09 SchemaExport - user lacks privilege or
object not found: PUBLIC.BLC_ADDITIONAL_OFFER_INFO

I see this on most of the tables. Could you point me in the right direction
to understand/resolve the above issue?

Thanks,
Bhaskar

**Comment by iceliu** [comment]
I also can not work with Maven 3.3.3, like bmulpuri's say, it will have M2_HOME environment variable issue. I set maven.home=/usr/local/Cellar/maven/3.2.5/libexec in build.properites (I use MacOS), it works find win command line mod. Thank you guys, you save my lots of time.

**Comment by phillipuniverse** [comment]
For Maven 3.3.3, set this property in build.xml:

``` xml
<jvmarg value="-Dmaven.multiModuleProjectDirectory=maven.home>" />
```

We will be updating this in the default workspace download.

Closing this I think this is done.
