### ISSUE TITLE
Cannot compile OOB with Maven 3.3

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/LegacyDemoSite#168]
Error:

``` console
Buildfile: /home/developer/Documentos/eclipse-workspace/DemoSite/site/build.xml
jetty-demo-no-db:
[artifact:mvn] Listening for transport dt_socket at address: 8000
[artifact:mvn] -Dmaven.multiModuleProjectDirectory system propery is not set. Check $M2_HOME environment variable and mvn script match.
[artifact:mvn] Java Result: 1
```

It seems that with Maven 3.3 they have discouraged use of multi-module projects. From http://forum.broadleafcommerce.org/viewtopic.php?f=14&t=4233 it seems like this is easily fixed by adding this JVM parameter:

``` xml
<jvmarg value="-Dmaven.multiModuleProjectDirectory=$M2_HOME" />
```

But it seems like additional research on this topic is that the project directory should be the root of the multi-module project itself, which seems like that would mean:

``` xml
<jvmarg value="-Dmaven.multiModuleProjectDirectory=$project.root" />
```

Not exactly sure. Needs a bit more research.

**Comment by atamanroman** [comment]
Bug with m2e and mvn 3.3. Should be fixed soon: https://bugs.eclipse.org/bugs/show_bug.cgi?id=462944

I just downgraded to 3.2 until then.

Btw: it's $project.root and not $M2_HOME. However, it seems that setting that property is all that's needed, regardless where it's pointing at.
