### ISSUE TITLE
'tomcat-stop' ant task seems not to work

### ISSUE THREAD

**Issue by tonyobanon** [BroadleafCommerce/LegacyDemoSite#172]
Hi, I am relatively new to broadleaf commerce. After completing the setup procedures at http://www.broadleafcommerce.com/docs/core/current/getting-started, I started the tomcat server by running the 'tomcat' ant task located at [DemoSite/site/build.xml] and the server started successfully.
But running the 'tomcat-stop' task seems not to work. The site still comes up in the browser, after executing 'tomcat-stop' (for both admin and site)

This is logged in the console

Buildfile: C:\Users\Tony\eclipse-workspace\DemoSite\site\build.xml
tomcat-stop:
[artifact:mvn] [INFO] Scanning for projects...
[artifact:mvn] [INFO]  
[artifact:mvn] [INFO] ------------------------------------------------------------------------
[artifact:mvn] [INFO] Building site 1.0
[artifact:mvn] [INFO] ------------------------------------------------------------------------
[artifact:mvn] [INFO] 
[artifact:mvn] [INFO] --- tomcat7-maven-plugin:2.2:shutdown (default-cli) @ site ---
[artifact:mvn] [INFO] ------------------------------------------------------------------------
[artifact:mvn] [INFO] BUILD SUCCESS
[artifact:mvn] [INFO] ------------------------------------------------------------------------
[artifact:mvn] [INFO] Total time: 7.709 s
[artifact:mvn] [INFO] Finished at: 2015-06-13T22:02:29+01:00
[artifact:mvn] [INFO] Final Memory: 17M/169M
[artifact:mvn] [INFO] ------------------------------------------------------------------------
[artifact:mvn] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024M; support was removed in 8.0
BUILD SUCCESSFUL
Total time: 14 seconds

But it seems nothing happens after on.. The site still comes up in the browser

I need to know what to do to shutdown tomcat..
Thanks

**Comment by phillipuniverse** [comment]
Not sure why that maven task doesn't work; maybe because it's in a forked instance?

At any rate, you can just kill the process that started Tomcat up. For instance if you ran `ant tomcat` in the command line, just ctrl + c to kill the process. If you are running it from the ant commants in Eclipse, just hit the red box to kill the process.

I'll leave this open for additional investigation from us.

**Comment by daniellavoie** [comment]
Hello,

I confirm that I encountered the same issue. Killing the ant task from Eclipse Debug tab isn't enough. I had to kill the java process from the Process Manager. If I get some time I might also try to investigate.

Personnaly, I replicated the ant task parameters to a dedicated Run Configuration. As a result, no more needed to use remote debuging.

**Comment by okoky88** [comment]
Hello @daniellavoie can you please tell me how you managed to replicate the ant task to a dedicated run configuration? I am trying but did not succeed so far.

**Comment by daniellavoie** [comment]
Hi @okoky88 

You need a Maven build launch configuration with the goal **tomcat7:run**. Then, inside the JRE tab, configure the following VM arguments : 

-XX:MaxPermSize=256M
-Xmx1024M
-Drebel.root=../../
-noverify
-Drebel.check_class_hash=true
-javaagent:../lib/spring-instrument-4.1.6.RELEASE.jar
-Druntime.environment=development
-Ddatabase.user=**yourDatabaseUserName**
-Ddatabase.password=**yourDatabasePAssword**
-Ddatabase.driver=**yourDatabaseDriver**
-Ddatabase.url=**yourDatabaseJdbcUrl**

Have fun !

**Comment by okoky88** [comment]
Thanks a lot @daniellavoie, worked like a charm.

Do you have any idea how to do the same with gradle?

**Comment by daniellavoie** [comment]
You'll have to use a different plugin than maven's tomcat7. I think a similar one can be found for gradle. I ain't a gradle expert but I supposed you'll have to rewrite the pom.xml for your gradle build.
