### ISSUE TITLE
Problem switching to MySQL (seeking help interpreting Broadleaf log entries)

### ISSUE THREAD

**Issue by blondeMatrix** [BroadleafCommerce/LegacyDemoSite#176]
Hello to the Broadleaf community,

I am attempting to build and deploy Broadleaf for evaluation. Building the DemoSite project in IntelliJ IDEA appears to go fine. The point where I run into difficulties is when reconfiguring Broadleaf to use MySQL rather than HSQLDB. This is despite carefully following your documentation on the changeover (though I'm finding the directions a little unclear in places). I'm hoping that someone can help identify the cause/solution, based on the log output:

http://assets.optomus.com/documents/broadleaf.log

I'm happy to provide my configuration settings if necessary, though these are largely based on the abovementioned instructions relating to MySQL.

Thanks in advance for your response,

Chris.

**Comment by phillipuniverse** [comment]
Answered in the forums at http://forum.broadleafcommerce.org/viewtopic.php?f=14&t=4396.
