### ISSUE TITLE
Ant build can't fetch dependencies from maven local repository.

### ISSUE THREAD

**Issue by hanrw** [BroadleafCommerce/LegacyDemoSite#18]
Buildfile: D:\opensource\DemoSite\site\build.xml
start-db:
[artifact:dependencies] Downloading: com/mycompany/core/1.0/core-1.0.pom from repository public snapshots at http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'com.mycompany:core:pom:1.0' in repository public snapshots (http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/)
[artifact:dependencies] Downloading: com/mycompany/core/1.0/core-1.0.pom from repository public releases at http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'com.mycompany:core:pom:1.0' in repository public releases (http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/)
[artifact:dependencies] Downloading: com/mycompany/core/1.0/core-1.0.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'com.mycompany:core:pom:1.0' in repository central (http://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: com/mycompany/core/1.0/core-1.0.jar from repository public snapshots at http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'com.mycompany:core:jar:1.0' in repository public snapshots (http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/)
[artifact:dependencies] Downloading: com/mycompany/core/1.0/core-1.0.jar from repository public releases at http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'com.mycompany:core:jar:1.0' in repository public releases (http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/)
[artifact:dependencies] Downloading: com/mycompany/core/1.0/core-1.0.jar from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'com.mycompany:core:jar:1.0' in repository central (http://repo1.maven.org/maven2)
[artifact:dependencies] An error has occurred while processing the Maven artifact tasks.
[artifact:dependencies]  Diagnosis:
[artifact:dependencies] 
[artifact:dependencies] Unable to resolve artifact: Missing:
[artifact:dependencies] ----------
[artifact:dependencies] 1) com.mycompany:core:jar:1.0
[artifact:dependencies] 
[artifact:dependencies]   Try downloading the file manually from the project website.
[artifact:dependencies] 
[artifact:dependencies]   Then, install it using the command: 
[artifact:dependencies]       mvn install:install-file -DgroupId=com.mycompany -DartifactId=core -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file
[artifact:dependencies] 
[artifact:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:dependencies]       mvn deploy:deploy-file -DgroupId=com.mycompany -DartifactId=core -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:dependencies] 
[artifact:dependencies]   Path to dependency: 
[artifact:dependencies]     1) com.mycompany:site:war:1.0
[artifact:dependencies]     2) com.mycompany:core:jar:1.0
[artifact:dependencies] 
[artifact:dependencies] ----------
[artifact:dependencies] 1 required artifact is missing.
[artifact:dependencies] 
[artifact:dependencies] for artifact: 
[artifact:dependencies]   com.mycompany:site:war:1.0
[artifact:dependencies] 
[artifact:dependencies] from the specified remote repositories:
[artifact:dependencies]   central (http://repo1.maven.org/maven2),
[artifact:dependencies]   public snapshots (http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/),
[artifact:dependencies]   public releases (http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/)
[artifact:dependencies] 
[artifact:dependencies] 
[artifact:dependencies] 

BUILD FAILED
## D:\opensource\DemoSite\site\build.xml:93: Unable to resolve artifact: Missing:

1) com.mycompany:core:jar:1.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.mycompany -DartifactId=core -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.mycompany -DartifactId=core -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) com.mycompany:site:war:1.0
    2) com.mycompany:core:jar:1.0

---

1 required artifact is missing.

for artifact: 
  com.mycompany:site:war:1.0

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  public snapshots (http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/),
  public releases (http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/)

Total time: 5 seconds

**Comment by hanrw** [comment]
```
  Fix this by change  <target name="start-db"> 
   <artifact:dependencies filesetId="warDeps" pomRefId="warPom" useScope="test" >
        <localrepository path="D:\\.m2\\repository"/>
    </artifact:dependencies>
```

**Comment by phillipuniverse** [comment]
This seems like an issue only if you did not previously install the 'core' module which is a required dependency of both site and admin.
