### ISSUE TITLE
ImportScriptException

### ISSUE THREAD

**Issue by bxsw** [BroadleafCommerce/LegacyDemoSite#185]
org.hibernate.tool.hbm2ddl.ImportScriptException: Error during statement execution (file: '/config/bc/sql/load_admin_roles.sql'): INSERT INTO BLC_ADMIN_ROLE (ADMIN_ROLE_ID, DESCRIPTION, NAME, DATE_UPDATED) VALUES (-1,'Admin Master Access','ROLE_ADMIN', CURRENT_TIMESTAMP)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'DATE_UPDATED' in 'field list

broadleaf-framework-5.0.0-GA.jar

**Comment by phillipuniverse** [comment]
This should be fixed in Broadleaf 5.2 with https://github.com/BroadleafCommerce/CommunityDemo.
