### ISSUE TITLE
No Blank in Admin Menu?

### ISSUE THREAD

**Issue by SantoDE** [BroadleafCommerce/LegacyDemoSite#186]
Hey there,

I'm currently implementing my own admin section but I'm struggling a little. 

This is my admin_module record: 

![image](https://cloud.githubusercontent.com/assets/1031255/16815069/c46fd2e4-4938-11e6-837b-3644f77334ef.png)

However, the header of the popup is displayed by the key and not by the name. Shouldn't it be the name?

![image](https://cloud.githubusercontent.com/assets/1031255/16815021/984e6f22-4938-11e6-9c11-3c611144ba11.png)

Any help? @phillipuniverse maybe? :-)

Thanks!

Regards,
SantoDE

**Comment by Jerry77oz** [comment]
Answered via the broadleaf forums here: http://forum.broadleafcommerce.org/viewtopic.php?f=13&t=25342
