### ISSUE TITLE
Upload Asset doesn't work?

### ISSUE THREAD

**Issue by SantoDE** [BroadleafCommerce/LegacyDemoSite#187]
Hey there,

I've got another small Issue. Whenever I click in the admin menu "Content => Media Assets => Upload Assets" nothing happens. Sadly, I don't have any errors in neither my server log nor in the browser log. 

Anyone got a clue?

Thanks

**Comment by Jerry77oz** [comment]
Closing and opening up an internal issue. Follow can be found on the forums: http://forum.broadleafcommerce.org/viewtopic.php?f=13&t=25343&p=50745#p50745

**Comment by sumittech17** [comment]
Is it fixed now ?
