### ISSUE TITLE
NPE when adding new page in admin

### ISSUE THREAD

**Issue by ghost** [BroadleafCommerce/LegacyDemoSite#188]
When I tried to add new page i received message:

![zaznaczenie_074](https://cloud.githubusercontent.com/assets/11396480/17140016/1d314710-5347-11e6-9cf9-8a191e0f4803.png)

**Comment by regcole** [comment]
Adding this ticket to [QA](https://github.com/BroadleafCommerce/QA/issues/2030) Sprint Backlog.

**Comment by danielcolgrove** [comment]
Reopening this issue.  We'll want to continue to track the issue here and will update this issue once the fix is in place.

**Comment by danielcolgrove** [comment]
This issue has been addressed on the 5.0.3-GA release.  This is now available as a release: https://github.com/BroadleafCommerce/DemoSite/releases
