### ISSUE TITLE
Exceptions while trying to run  the Demo site in local

### ISSUE THREAD

**Issue by DhanaTontanahal** [BroadleafCommerce/LegacyDemoSite#189]
I am facing exceptions like
connect exception
beancreation exception
sql.transientconnectexception

Can you please help me in getting through these exceptions..
![blerror1](https://cloud.githubusercontent.com/assets/16509095/17837948/cb5f6fe2-67dd-11e6-8822-13b8828f4057.PNG)

**Comment by DhanaTontanahal** [comment]
I tried the fix on the forum which says that do mvn clean install i did it and also mvn clean install is fine
when i am trying to run startadmin.bat or startsite.bat im facingthese issues.

Thank you.

**Comment by cja769** [comment]
It doesn't look like it's finding a database to connect to

**Comment by danielcolgrove** [comment]
Not sure if you were able to get the database connectivity resolved.  For community support questions please use either the broadleaf forum (forum.broadleafcommerce.org) or stackoverflow tagged with broadleaf-commerce (http://stackoverflow.com/questions/tagged/broadleaf-commerce).
