### ISSUE TITLE
When visit http://localhost:8081/admin/ said:user lacks privilege or object not found: BLC_LOCALE

### ISSUE THREAD

**Issue by hanrw** [BroadleafCommerce/LegacyDemoSite#19]
[artifact:mvn] org.hibernate.exception.SQLGrammarException: user lacks privilege or object not found: BLC_LOCALE
[artifact:mvn]  at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:82)
[artifact:mvn]  at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
[artifact:mvn]  at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
[artifact:mvn]  at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
[artifact:mvn]  at org.hibernate.engine.jdbc.internal.proxy.ConnectionProxyHandler.continueInvocation(ConnectionProxyHandler.java:146)
[artifact:mvn]  at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
[artifact:mvn]  at $Proxy163.prepareStatement(Unknown Source)
[artifact:mvn]  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:147)
[artifact:mvn]  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:166)
[artifact:mvn]  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:145)
[artifact:mvn]  at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1854)
[artifact:mvn]  at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1831)
[artifact:mvn]  at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1811)
[artifact:mvn]  at org.hibernate.loader.Loader.doQuery(Loader.java:899)
[artifact:mvn]  at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:341)
[artifact:mvn]  at org.hibernate.loader.Loader.doList(Loader.java:2516)
[artifact:mvn]  at org.hibernate.loader.Loader.listUsingQueryCache(Loader.java:2361)
[artifact:mvn]  at org.hibernate.loader.Loader.list(Loader.java:2324)
[artifact:mvn]  at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:490)
[artifact:mvn]  at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)
[artifact:mvn]  at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195)
[artifact:mvn]  at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1247)
[artifact:mvn]  at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
[artifact:mvn]  at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:264)
[artifact:mvn]  at org.broadleafcommerce.common.locale.dao.LocaleDaoImpl.findDefaultLocale(LocaleDaoImpl.java:71)
[artifact:mvn]  at org.broadleafcommerce.common.locale.service.LocaleServiceImpl.findDefaultLocale(LocaleServiceImpl.java:46)
[artifact:mvn]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[artifact:mvn]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[artifact:mvn]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[artifact:mvn]  at java.lang.reflect.Method.invoke(Method.java:597)
[artifact:mvn]  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
[artifact:mvn]  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
[artifact:mvn]  at $Proxy106.findDefaultLocale(Unknown Source)
[artifact:mvn]  at org.broadleafcommerce.common.web.BroadleafLocaleResolverImpl.resolveLocale(BroadleafLocaleResolverImpl.java:98)
[artifact:mvn]  at org.broadleafcommerce.openadmin.web.filter.BroadleafAdminRequestProcessor.process(BroadleafAdminRequestProcessor.java:71)
[artifact:mvn]  at org.broadleafcommerce.openadmin.web.filter.BroadleafAdminRequestFilter.doFilterInternal(BroadleafAdminRequestFilter.java:58)
[artifact:mvn]  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:180)
[artifact:mvn]  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:166)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
[artifact:mvn]  at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
[artifact:mvn]  at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
[artifact:mvn]  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1302)
[artifact:mvn]  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:448)
[artifact:mvn]  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
[artifact:mvn]  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
[artifact:mvn]  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
[artifact:mvn]  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1067)
[artifact:mvn]  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:377)
[artifact:mvn]  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
[artifact:mvn]  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1001)
[artifact:mvn]  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
[artifact:mvn]  at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
[artifact:mvn]  at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
[artifact:mvn]  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
[artifact:mvn]  at org.eclipse.jetty.server.Server.handle(Server.java:360)
[artifact:mvn]  at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
[artifact:mvn]  at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890)
[artifact:mvn]  at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944)
[artifact:mvn]  at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630)
[artifact:mvn]  at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
[artifact:mvn]  at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
[artifact:mvn]  at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:622)
[artifact:mvn]  at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
[artifact:mvn]  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
[artifact:mvn]  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
[artifact:mvn]  at java.lang.Thread.run(Thread.java:662)
[artifact:mvn] Caused by: 
[artifact:mvn] java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: BLC_LOCALE
[artifact:mvn]  at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
[artifact:mvn]  at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
[artifact:mvn]  at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
[artifact:mvn]  at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
[artifact:mvn]  at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:248)
[artifact:mvn]  at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareStatement(PoolingDataSource.java:302)
[artifact:mvn]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[artifact:mvn]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[artifact:mvn]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[artifact:mvn]  at java.lang.reflect.Method.invoke(Method.java:597)
[artifact:mvn]  at org.hibernate.engine.jdbc.internal.proxy.ConnectionProxyHandler.continueInvocation(ConnectionProxyHandler.java:138)
[artifact:mvn]  at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
[artifact:mvn]  at $Proxy163.prepareStatement(Unknown Source)
[artifact:mvn]  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:147)
[artifact:mvn]  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:166)
[artifact:mvn]  at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:145)
[artifact:mvn]  at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1854)
[artifact:mvn]  at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1831)
[artifact:mvn]  at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1811)
[artifact:mvn]  at org.hibernate.loader.Loader.doQuery(Loader.java:899)
[artifact:mvn]  at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:341)
[artifact:mvn]  at org.hibernate.loader.Loader.doList(Loader.java:2516)
[artifact:mvn]  at org.hibernate.loader.Loader.listUsingQueryCache(Loader.java:2361)
[artifact:mvn]  at org.hibernate.loader.Loader.list(Loader.java:2324)
[artifact:mvn]  at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:490)
[artifact:mvn]  at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)
[artifact:mvn]  at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195)
[artifact:mvn]  at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1247)
[artifact:mvn]  at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
[artifact:mvn]  at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:264)
[artifact:mvn]  at org.broadleafcommerce.common.locale.dao.LocaleDaoImpl.findDefaultLocale(LocaleDaoImpl.java:71)
[artifact:mvn]  at org.broadleafcommerce.common.locale.service.LocaleServiceImpl.findDefaultLocale(LocaleServiceImpl.java:46)
[artifact:mvn]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[artifact:mvn]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[artifact:mvn]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[artifact:mvn]  at java.lang.reflect.Method.invoke(Method.java:597)
[artifact:mvn]  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
[artifact:mvn]  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
[artifact:mvn]  at $Proxy106.findDefaultLocale(Unknown Source)
[artifact:mvn]  at org.broadleafcommerce.common.web.BroadleafLocaleResolverImpl.resolveLocale(BroadleafLocaleResolverImpl.java:98)
[artifact:mvn]  at org.broadleafcommerce.openadmin.web.filter.BroadleafAdminRequestProcessor.process(BroadleafAdminRequestProcessor.java:71)
[artifact:mvn]  at org.broadleafcommerce.openadmin.web.filter.BroadleafAdminRequestFilter.doFilterInternal(BroadleafAdminRequestFilter.java:58)
[artifact:mvn]  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:180)
[artifact:mvn]  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:166)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
[artifact:mvn]  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
[artifact:mvn]  at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
[artifact:mvn]  at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
[artifact:mvn]  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1302)
[artifact:mvn]  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:448)
[artifact:mvn]  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
[artifact:mvn]  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
[artifact:mvn]  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
[artifact:mvn]  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1067)
[artifact:mvn]  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:377)
[artifact:mvn]  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
[artifact:mvn]  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1001)
[artifact:mvn]  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
[artifact:mvn]  at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
[artifact:mvn]  at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
[artifact:mvn]  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
[artifact:mvn]  at org.eclipse.jetty.server.Server.handle(Server.java:360)
[artifact:mvn]  at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
[artifact:mvn]  at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890)
[artifact:mvn]  at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944)
[artifact:mvn]  at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630)
[artifact:mvn]  at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
[artifact:mvn]  at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
[artifact:mvn]  at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:622)
[artifact:mvn]  at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
[artifact:mvn]  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
[artifact:mvn]  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
[artifact:mvn]  at java.lang.Thread.run(Thread.java:662)
[artifact:mvn] [ WARN] 10:07:41 SqlExceptionHelper - SQL Error: -5501, SQLState: 42501
[artifact:mvn] [ERROR] 10:07:41 SqlExceptionHelper - user lacks privilege or object not found: BLC_LOCALE

**Comment by jefffischer** [comment]
This usually means that your database was not populated at startup with the various import sql scripts. Can you confirm your database has any data after startup? Check your blPU.hibernate.hbm2ddl.auto value (see http://docs.broadleafcommerce.org/core/current/broadleaf-concepts/key-aspects-and-configuration/database-configuration)

**Comment by phillipuniverse** [comment]
See @jefffischer's comment for the fix.

By the way, the DemoSite admin project is configured by default to do nothing with the database, whereas the site project has the Hibernate ddl set to create-drop out of the box. On first run, you usually have to have both applications started up unless you change these ddl values.

**Comment by xiayx** [comment]
I meet this question too.I modify blPU.hibernate.hbm2ddl.auto=create-drop in 'runtime-properties/development.properties' ,everything right.
In the course of the [tutorial](http://www.broadleafcommerce.com/docs/core/current/broadleaf-concepts/key-aspects-and-configuration/database-configuration) ,it will be better to make this point more clearly.
