### ISSUE TITLE
Not allow user to create product instance of ProductImpl

### ISSUE THREAD

**Issue by mstelmaszuk** [BroadleafCommerce/LegacyDemoSite#192]
Hi, basically I wrote two classes which represents products in my sample store (extending ProductImpl from org.broadleafcommerce...) and added it to all configurations where it was needed. Now when I click button "Add product" on admin site modal windows displays me a list including Product, ProductBundle, MyProduct1, MyProduct2. I want to remove Product and ProductBundle (classes from org.broadleafcommerce..) from that list.

Is it possible?

**Comment by danielcolgrove** [comment]
Answered in stackoverflow - http://stackoverflow.com/questions/39485124/how-to-not-allow-admin-to-create-product-instance-of-productimpl

**Comment by mstelmaszuk** [comment]
Thanks ;)
