### ISSUE TITLE
Met ClassCastException when try to extend Customer entity

### ISSUE THREAD

**Issue by lunasphere** [BroadleafCommerce/LegacyDemoSite#193]
I was trying to extend the Customer entity in my application based on DemoSite 5.0.1-GA. I had extended the original Customer interface and CustomerImpl class. Then added my CustomerImpl class into persistence-core.xml and applicationContext-entity.xml in the core project, overriding the bean with id "org.broadleafcommerce.profile.core.domain.Customer".

I could extend the Order entity successfully by these steps. But for the Customer entity, I found that I would always get an instance of org.broadleafcommerce.profile.core.domain.CustomerImpl, whether in relative entities like Order or directly get the "org.broadleafcommerce.profile.core.domain.Customer" bean from Spring context, but not an instance of my extended class as expected.

**Comment by danielcolgrove** [comment]
Please use either the broadleaf forum (forum.broadleafcommerce.org) or stackoverflow tagged with broadleaf-commerce (http://stackoverflow.com/questions/tagged/broadleaf-commerce) for community support questions.
