### ISSUE TITLE
DemoSite pom.xml references snapshot versions but not snapshot repo

### ISSUE THREAD

**Issue by ghost** [BroadleafCommerce/LegacyDemoSite#2]
After git clone https://github.com/BroadleafCommerce/DemoSite.git dependency resolution fails.

In DemoSite/pom.xml blc.version is set to <blc.version>2.1.1-SNAPSHOT</blc.version>. However, under <repositories>, only http://www.broadleafcommerce.org/nexus/content/repositories/releases/ is added so -SNAPSHOTS are unavailable. Locally temporarily resolved by adding the snapshot repo, eg:

```
<repositories>
    <repository>
        <id>public releases</id>
        <name>public releases</name>
        <url>http://www.broadleafcommerce.org/nexus/content/repositories/releases/</url>
    </repository>
    <repository>
        <id>public snapshots</id>
        <name>public snapshots</name>
        <url>http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/</url>
    </repository>        
</repositories>
```

In the DemoSite bundled with the eclipse-workspace zip file (as referenced by 'Getting Started') this problem doesn't exist because the blc.version is <blc.version>2.0.2-GA</blc.version> a release version.

**Comment by phillipuniverse** [comment]
Thanks for the issue, sorry it took so long to actually comment on it!

We have now included both repositories in the root pom definition so I'm going to go ahead and close this issue.
