### ISSUE TITLE
Can't add roles in blc.version 5.0.5.-GA

### ISSUE THREAD

**Issue by disano357** [BroadleafCommerce/LegacyDemoSite#200]
In admin, when trying to add a role or permission, I get the following exception:
java.lang.NullPointerException
org.broadleafcommerce.openadmin.web.controller.entity.AdminBasicEntityController.buildAddCollectionItemModel(AdminBasicEntityController.java:1263)

I rolled back to 5.0.3.-GA version, where adding the roles works.

**Comment by ChrisNail** [comment]
This issue has has been previously reported. See BroadleafCommerce/QA#2358 for further details

**Comment by disano357** [comment]
When I click on the link, I get a 404 message. Did you paste the correct link?

**Comment by danielcolgrove** [comment]
Sorry disano357, Chris posted an private/internal link.  We can confirm that this is an issue and we have opened an issue for this to be addressed.  This will likely be addressed in 5.0.7-GA.

**Comment by hugolam008** [comment]
hi disano357, the demo site can not be started up from intellij even though following the tutorial. 
Info: jdk1.8; tomcat 9; demo version 5.0.1-GA .
Any ideas?

**Comment by phillipuniverse** [comment]
This should be fixed in Broadleaf 5.2 with https://github.com/BroadleafCommerce/CommunityDemo.
