### ISSUE TITLE
The online demo can not new an offer

### ISSUE THREAD

**Issue by a1197319946** [BroadleafCommerce/LegacyDemoSite#202]

**Comment by danielcolgrove** [comment]
Are you receiving an error when trying to add a new offer.  I just tested and was able to save it okay.

**Comment by a1197319946** [comment]
Thx.It run well right now . :) But can you tell me what the version run at the online demo ? Can i run it in my local enviroment?

**Comment by a1197319946** [comment]
Thx.It run well right now . :) But can you tell me what the version run at the online demo ? Can i run it in my local environment?

**Comment by danielcolgrove** [comment]
The DemoSite currently has 5.0 but more specifically it is our Enterprise edition.  The community edition is downloadable.  See the Run BLC Locally link on our Getting Started page.

http://www.broadleafcommerce.com/docs/core/current/getting-started
