### ISSUE TITLE
media tab in category and product not rendering

### ISSUE THREAD

**Issue by disano357** [BroadleafCommerce/LegacyDemoSite#204]
On the out of the box DemoSite, version 5.0.3-GA.jar

When opening an category or product, when selecting the Media tab, the no images are shown. When you try to add an image, you can added and it is stored, but it is not shown.
You can get to the image via the url.

my log gives me this:

> 2017-jan-19 12:48:47,385 [http-bio-8081-exec-6] org.broadleafcommerce.openadmin.web.controller.entity.AdminBasicOperationsController 
  ERROR [JS] - (http://localhost:8081/admin/js/admin/components/entityForm.js:340) - Uncaught TypeError: Cannot read property 'initialize' of undefined

I did find a similar issue:
[https://github.com/BroadleafCommerce/BroadleafCommerce/issues/1236](url)

But no solution. Any suggestion?

**Comment by benhenda89** [comment]
the same problem for me

**Comment by phillipuniverse** [comment]
This should be fixed in https://github.com/BroadleafCommerce/CommunityDemo with Broadleaf 5.2.
