### ISSUE TITLE
SolrHelperServiceImpl - Could not determine core names for the Solr Clients provided

### ISSUE THREAD

**Issue by tushargugnani** [BroadleafCommerce/LegacyDemoSite#206]
Stand Alone Solr Configuration is not working out of box with BC v5. Throws error on rebuildIndex while Core Swap.

**Comment by phillipuniverse** [comment]
@tushargugnani can you verify on our new starting point at https://github.com/BroadleafCommerce/CommunityDemo and open an issue there if you still have problems?
