### ISSUE TITLE
Error on Adding New Asset via StaticAssetService

### ISSUE THREAD

**Issue by tushargugnani** [BroadleafCommerce/LegacyDemoSite#210]
org.broadleafcommerce.common.audit.AbstractAuditableListener.setAuditData(AbstractAuditableListener.java:88) at org.broadleafcommerce.common.audit.AbstractAuditableListener.setAuditCreationData(AbstractAuditableListener.java:71) at org.broadleafcommerce.openadmin.audit.AdminAuditableListener.setAuditCreationAndUpdateData(AdminAuditableListener.java:33) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.hibernate.ejb.event.ListenerCallback.invoke(ListenerCallback.java:48) at org.hibernate.ejb.event.EntityCallbackHandler.callback(EntityCallbackHandler.java:110) at org.hibernate.ejb.event.EntityCallbackHandler.preCreate(EntityCallbackHandler.java:79) at org.hibernate.ejb.event.EJB3MergeEventListener.saveWithGeneratedId(EJB3MergeEventListener.java:70) at org.hibernate.event.internal.DefaultMergeEventListener.saveTransientEntity(DefaultMergeEventListener.java:236) at org.hibernate.event.internal.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:216) at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:154) at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:76) at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:903) at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:887) at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:891) at org.hibernate.ejb.AbstractEntityManagerImpl.merge(AbstractEntityManagerImpl.java:889) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at

**Comment by tushargugnani** [comment]
In tomcat 7 ,this issue is because of missing -javaagent:path/to/spring-instrument.jar while starting tomcat.
I have hosted my webapp on tomcat 8 ,and even on passing the required spring-instrument.jar (for load time weaving) this thing does not seem to work.

**Comment by phillipuniverse** [comment]
@tushargugnani can you verify on our new starting point, https://github.com/BroadleafCommerce/CommunityDemo and see if you still have an issue?
