### ISSUE TITLE
Accented characters are not correctly rendered on input fields 

### ISSUE THREAD

**Issue by linuxidefix** [BroadleafCommerce/LegacyDemoSite#211]
Screenshot [http://imgur.com/a/EP8cr](http://imgur.com/a/EP8cr)
Tested on Chrome and Firefox
Can be reproduced on live demo (blc 5.x)
Steps to reproduce it: 
1) select Change language to French ( in the header )
2) add a product to the cart
3) display the mini cart

The value displayed is the raw html value instead of "Mettre à jour"

**Comment by phillipuniverse** [comment]
Moved this to BroadleafCommerce/CommunityDemo#10
