### ISSUE TITLE
URL's point to 127.0.0.1

### ISSUE THREAD

**Issue by karlmarxrichards** [BroadleafCommerce/LegacyDemoSite#216]
Using 5.1.2

After I deploy the war file to Tomcat /shop, the links to Sort, Page and Manufacturer point to 127.0.0.1, not to the context of the application.

**Comment by phillipuniverse** [comment]
Not sure what's going on here, can you verify on https://github.com/BroadleafCommerce/CommunityDemo?

**Comment by karlmarxrichards** [comment]
The link you provided is invalid.  What would you like me to verify?

**Comment by phillipuniverse** [comment]
Sorry about that, I updated the link. I was just going through and cleaning up some old issues in this repository and referring you to the other starting point.

I'm not sure I understand your issue totally, can you post a screenshot?

**Comment by karlmarxrichards** [comment]
I have my demo located here:
https://www.zdslogic.com/shop/products

Hover over the links to Sort, Page and Manufacturer and you will see that these links point to 127.0.0.1:9090 not https://www.zdslogic.com/shop/products.

Does that help you understand the issue?
