### ISSUE TITLE
pom.xml can do with some updating

### ISSUE THREAD

**Issue by watermelonjuice** [BroadleafCommerce/LegacyDemoSite#31]
http://www.versioneye.com/services/5256fa8f632bac53a7007fbe

**Comment by phillipuniverse** [comment]
Didn't know about this versioneye tool, thanks for the reference. Which pom did you upload to run this?

Just to copy the results here for easy reference:

> | Current | Locked | Dependency |
> | --- | --- | --- |
> | 7.0.42 | 7.0.30 | tomcat-jdbc |
> | 1.4 | 1.2.2 | commons-dbcp |
> | 2.3.0 | 2.2.4 | hsqldb |
> | 6.8.7 | 5.9 | testng |

HSQLDB could probably be upgraded without worrying about messing anything up. For `tomcat-jdbc` and `commons-jdbc`, those should arguably be managed by what Tomcat version you are deploying on anyway so... These don't really seem like any priority on updating within DemoSIte.

For TestNG, we know we are definitely behind on our test coverage (JUnit is the same story) and upgrading from the version that we are on to the latest version will not be trivial and will have to be apart of a larger testing refocus.

**Comment by watermelonjuice** [comment]
I used the 3.0.2 version.

**Comment by watermelonjuice** [comment]
VersionEye can watch the github project if you login and tell it to.
