### ISSUE TITLE
Unable to register for an account after successfully completing a Guest Checkout using the same email.

### ISSUE THREAD

**Issue by elbertbautista** [BroadleafCommerce/LegacyDemoSite#38]
Scenario:

1) Checkout as guest using email "test@test.com"
2) Come back to the site later, and try to register for an account using "test@test.com"

You get this:
![screen shot 2013-11-01 at 9 10 54 am](https://f.cloud.github.com/assets/1213999/1453927/77db1052-42ff-11e3-98a5-788de9a7bc29.png)

Possible business requirements:
1) "test@test.com" sees previous "guest" orders in their order history after successfully registering.
2) "test@test.com does NOT see any "guest" checkouts in their order history after successfully registering

**Comment by phillipuniverse** [comment]
@elbertbautista the business req part is captured in #22

**Comment by elbertbautista** [comment]
This may only apply to private demo -
