### ISSUE TITLE
Error while starting jetty demo Server

### ISSUE THREAD

**Issue by Arthiselvam** [BroadleafCommerce/LegacyDemoSite#45]
Hi, 
 I have downloaded the demo-site of broadleaf and successfully built maven.But when i am starting jetty server i get the following error.

Buildfile: D:\broadleaf\DemoSite\site\build.xml
     [echo] user Home
     [echo] C:\Users\715801
     [echo] maven home
     [echo] ${maven.home}
     [echo] ${build.properties}
start-db:
[artifact:dependencies] Downloading: com/broadleaf/core/1.0/core-1.0.pom from repository public snapshots at http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/
[artifact:dependencies] Error transferring file: Connection timed out: connect
[artifact:dependencies] [WARNING] Unable to get resource 'com.broadleaf:core:pom:1.0' from repository public snapshots (http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/): Error transferring file: Connection timed out: connect
[artifact:dependencies] Downloading: com/broadleaf/core/1.0/core-1.0.pom from repository public releases at http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/
[artifact:dependencies] Error transferring file: Connection timed out: connect
[artifact:dependencies] [WARNING] Unable to get resource 'com.broadleaf:core:pom:1.0' from repository public releases (http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/): Error transferring file: Connection timed out: connect
[artifact:dependencies] Downloading: com/broadleaf/core/1.0/core-1.0.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Connection timed out: connect
[artifact:dependencies] [WARNING] Unable to get resource 'com.broadleaf:core:pom:1.0' from repository central (http://repo1.maven.org/maven2): Error transferring file: Connection timed out: connect
[artifact:dependencies] Downloading: org/broadleafcommerce/broadleaf-framework-web/3.0.5-GA/broadleaf-framework-web-3.0.5-GA.pom from repository public snapshots at http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/
[artifact:dependencies] Error transferring file: Connection timed out: connect
[artifact:dependencies] [WARNING] Unable to get resource 'org.broadleafcommerce:broadleaf-framework-web:pom:3.0.5-GA' from repository public snapshots (http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/): Error transferring file: Connection timed out: connect
[artifact:dependencies] Downloading: org/broadleafcommerce/broadleaf-framework-web/3.0.5-GA/broadleaf-framework-web-3.0.5-GA.pom from repository public releases at http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/
[artifact:dependencies] Error transferring file: Connection timed out: connect
[artifact:dependencies] [WARNING] Unable to get resource 'org.broadleafcommerce:broadleaf-framework-web:pom:3.0.5-GA' from repository public releases (http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/): Error transferring file: Connection timed out: connect
[artifact:dependencies] Downloading: org/broadleafcommerce/broadleaf-framework-web/3.0.5-GA/broadleaf-framework-web-3.0.5-GA.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Connection timed out: connect
[artifact:dependencies] [WARNING] Unable to get resource 'org.broadleafcommerce:broadleaf-framework-web:pom:3.0.5-GA' from repository central (http://repo1.maven.org/maven2): Error transferring file: Connection timed out: connect
[artifact:dependencies] Downloading: org/broadleafcommerce/broadleaf-framework-web/3.0.5-GA/broadleaf-framework-web-3.0.5-GA.jar from repository public snapshots at http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/
[artifact:dependencies] Downloading: com/broadleaf/core/1.0/core-1.0.jar from repository public snapshots at http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/
[artifact:dependencies] Error transferring file: Connection timed out: connect
[artifact:dependencies] [WARNING] Unable to get resource 'org.broadleafcommerce:broadleaf-framework-web:jar:3.0.5-GA' from repository public snapshots (http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/): Error transferring file: Connection timed out: connect
[artifact:dependencies] Downloading: org/broadleafcommerce/broadleaf-framework-web/3.0.5-GA/broadleaf-framework-web-3.0.5-GA.jar from repository public releases at http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/
[artifact:dependencies] Error transferring file: Connection timed out: connect
[artifact:dependencies] [WARNING] Unable to get resource 'com.broadleaf:core:jar:1.0' from repository public snapshots (http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/): Error transferring file: Connection timed out: connect
[artifact:dependencies] Downloading: com/broadleaf/core/1.0/core-1.0.jar from repository public releases at http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/
[artifact:dependencies] Error transferring file: Connection timed out: connect
[artifact:dependencies] [WARNING] Unable to get resource 'org.broadleafcommerce:broadleaf-framework-web:jar:3.0.5-GA' from repository public releases (http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/): Error transferring file: Connection timed out: connect
[artifact:dependencies] Downloading: org/broadleafcommerce/broadleaf-framework-web/3.0.5-GA/broadleaf-framework-web-3.0.5-GA.jar from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Connection timed out: connect
[artifact:dependencies] [WARNING] Unable to get resource 'com.broadleaf:core:jar:1.0' from repository public releases (http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/): Error transferring file: Connection timed out: connect
[artifact:dependencies] Downloading: com/broadleaf/core/1.0/core-1.0.jar from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Connection timed out: connect
[artifact:dependencies] [WARNING] Unable to get resource 'org.broadleafcommerce:broadleaf-framework-web:jar:3.0.5-GA' from repository central (http://repo1.maven.org/maven2): Error transferring file: Connection timed out: connect
[artifact:dependencies] Error transferring file: Connection timed out: connect
[artifact:dependencies] [WARNING] Unable to get resource 'com.broadleaf:core:jar:1.0' from repository central (http://repo1.maven.org/maven2): Error transferring file: Connection timed out: connect
[artifact:dependencies] An error has occurred while processing the Maven artifact tasks.
[artifact:dependencies]  Diagnosis:
[artifact:dependencies] 
[artifact:dependencies] Unable to resolve artifact: Missing:
[artifact:dependencies] ----------
[artifact:dependencies] 1) org.broadleafcommerce:broadleaf-framework-web:jar:3.0.5-GA
[artifact:dependencies] 
[artifact:dependencies]   Try downloading the file manually from the project website.
[artifact:dependencies] 
[artifact:dependencies]   Then, install it using the command: 
[artifact:dependencies]       mvn install:install-file -DgroupId=org.broadleafcommerce -DartifactId=broadleaf-framework-web -Dversion=3.0.5-GA -Dpackaging=jar -Dfile=/path/to/file
[artifact:dependencies] 
[artifact:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:dependencies]       mvn deploy:deploy-file -DgroupId=org.broadleafcommerce -DartifactId=broadleaf-framework-web -Dversion=3.0.5-GA -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:dependencies] 
[artifact:dependencies]   Path to dependency: 
[artifact:dependencies]     1) com.broadleaf:site:war:1.0
[artifact:dependencies]     2) org.broadleafcommerce:broadleaf-framework-web:jar:3.0.5-GA
[artifact:dependencies] 
[artifact:dependencies] 2) com.broadleaf:core:jar:1.0
[artifact:dependencies] 
[artifact:dependencies]   Try downloading the file manually from the project website.
[artifact:dependencies] 
[artifact:dependencies]   Then, install it using the command: 
[artifact:dependencies]       mvn install:install-file -DgroupId=com.broadleaf -DartifactId=core -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file
[artifact:dependencies] 
[artifact:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:dependencies]       mvn deploy:deploy-file -DgroupId=com.broadleaf -DartifactId=core -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:dependencies] 
[artifact:dependencies]   Path to dependency: 
[artifact:dependencies]     1) com.broadleaf:site:war:1.0
[artifact:dependencies]     2) com.broadleaf:core:jar:1.0
[artifact:dependencies] 
[artifact:dependencies] ----------
[artifact:dependencies] 2 required artifacts are missing.
[artifact:dependencies] 
[artifact:dependencies] for artifact: 
[artifact:dependencies]   com.broadleaf:site:war:1.0
[artifact:dependencies] 
[artifact:dependencies] from the specified remote repositories:
[artifact:dependencies]   central (http://repo1.maven.org/maven2),
[artifact:dependencies]   public snapshots (http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/),
[artifact:dependencies]   public releases (http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/)
[artifact:dependencies] 
[artifact:dependencies] 
[artifact:dependencies] 

BUILD FAILED
## D:\broadleaf\DemoSite\site\build.xml:97: Unable to resolve artifact: Missing:

1) org.broadleafcommerce:broadleaf-framework-web:jar:3.0.5-GA

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.broadleafcommerce -DartifactId=broadleaf-framework-web -Dversion=3.0.5-GA -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.broadleafcommerce -DartifactId=broadleaf-framework-web -Dversion=3.0.5-GA -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) com.broadleaf:site:war:1.0
    2) org.broadleafcommerce:broadleaf-framework-web:jar:3.0.5-GA

2) com.broadleaf:core:jar:1.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.broadleaf -DartifactId=core -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.broadleaf -DartifactId=core -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) com.broadleaf:site:war:1.0
    2) com.broadleaf:core:jar:1.0

---

2 required artifacts are missing.

for artifact: 
  com.broadleaf:site:war:1.0

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  public snapshots (http://nexus.broadleafcommerce.org/nexus/content/repositories/snapshots/),
  public releases (http://nexus.broadleafcommerce.org/nexus/content/repositories/releases/)

Total time: 3 minutes 9 seconds

Kindly help me with this issue.
My maven Version is 3.1.1
I have installed Maven in D:\apache-maven-3.1.1 directory
i have set Build.Properties maven.home as : D:\apache-maven-3.1.1

I have the jars and war already downloaded in the following folders 
com.broadleaf:site:war:1.0:  D:\broadleaf\DemoSite\site\target : broadleaf.war

com.broadleaf:core:jar:1.0 :  D:.m2\repo\com\broadleaf\core\1.0 :core.jar

org.broadleafcommerce:broadleaf-framework-web:jar:3.0.5-GA                                  :     D:.m2\repo\org\broadleafcommerce\broadleaf-framework-web\3.0.5-GA  

Thanks,
Arthi

**Comment by phillipuniverse** [comment]
Do a full maven install from the root of the project to resolve this prior to running the `jetty-demo` ant task.
