### ISSUE TITLE
Can not update quality of bundles

### ISSUE THREAD

**Issue by watermelonjuice** [BroadleafCommerce/LegacyDemoSite#47]
1) Add a bundle to the cart
2) Update button does not work

Tested on 3.0.5GA. Will confirm if problem persists in .6

**Comment by watermelonjuice** [comment]
Bug still persists in .7

**Comment by phillipuniverse** [comment]
Can you post a stack trace here? And possibly identify if this is something in the framework or just incorrect data in demo site?

**Comment by phillipuniverse** [comment]
@watermelonjuice can you provide any additional details on this one?

**Comment by watermelonjuice** [comment]
Seems to be fixed. Probably caused by the other bundle items bug that was fixed recently.
