### ISSUE TITLE
Long Menu items in Template display poorly

### ISSUE THREAD

**Issue by carricraver** [BroadleafCommerce/LegacyDemoSite#65]
Moved from https://github.com/BroadleafCommerce/Enterprise/issues/60 Orginally filed by Ché.

In the sandbox preview mode, 'FAQs' is mispositioned. 
![image](https://f.cloud.github.com/assets/723674/1828488/56e57e7e-725b-11e3-8e6f-99372079b273.png)

Template needs better way of handling longer menu.
UX: Should alert user when item won't fit.

**Comment by watermelonjuice** [comment]
Is there any reason the template is using a fix width? What framework is the template built on as it isn't the most responsive code out there. (E.g. mobile view could do with improvement.)
