### ISSUE TITLE
Customer not displayed as logged in after successful login

### ISSUE THREAD

**Issue by lifliu** [BroadleafCommerce/LegacyDemoSite#67]
In latest release 3.0.7-GA, when register a new customer or log in an existing one, customer is still displayed as not logged in. However, customer information is displayed when access to the account page.

It can be reproduced in latest demo. After register a customer, customer is still displayed as not logged in but customer can be displayed correctly in /account page. Login an existing customer has the same problem.

**Comment by phillipuniverse** [comment]
This is a framework issue caused by the code from 66308746563e98e27d8bbce48d03fca2d47941db and so it only exists in 3.0.7-GA. Making a patch now, but I'm going to close this issue and open one in the framework.

**Comment by phillipuniverse** [comment]
Opened BroadleafCommerce/BroadleafCommerce#619, closing this.
