### ISSUE TITLE
Issues while trying to build and start the demo site

### ISSUE THREAD

**Issue by 77027subbu** [BroadleafCommerce/LegacyDemoSite#7]
The build goes good, however when I try to run the demo-jetty ant-task, I see the following error in the logs - [ERROR] 02:52:41 Ejb3Configuration - Container is providing a null PersistenceUnitRootUrl: discovery impossible. 

Can you please tell me, if I'm missing any step apart from what has been specified in the http://docs.broadleafcommerce.org/current/Getting-Started.html document.

I even see build path problems, 
- Project 'admin' is missing required Java project: 'core'
- Project 'combined' is missing required Java project: 'core'
- Project 'site' is missing required Java project: 'core'

Thanks for bringing up this excellent idea of a ecomm framework with all Open-Source tools & frameworks.

**Comment by phillipuniverse** [comment]
The first part is being tracked at BroadleafCommerce/BroadleafCommerce#58.

For your other issues, there might be a misconfiguration in your IDE (I assume Eclipse)? For those issues I recommend using the forums and supplying a few more details about your configuration.

**Comment by 77027subbu** [comment]
Thanks a lot. I switched using intellij over eclipse and the installation was smooth.
