### ISSUE TITLE
Search engine isn't working good. [SOLR]

### ISSUE THREAD

**Issue by karopodgajecki** [BroadleafCommerce/LegacyDemoSite#77]
Search engine (SOLR mode) don't work good for partials serach for example:

http://demo.broadleafcommerce.org/search?q=sauc - give us 0 results
http://demo.broadleafcommerce.org/search?q=sauce - give us 15 results 

Partial search don't work it should be something like sql: LIKE%

**Comment by ktisdell** [comment]
@spec8320 you can tune Solr any way that you like.  The demo site, out of the box, has a very simple Solr configuration.  There are many ways to get more out of Solr, and each implementor has different requirements.  You can use a wildcard to search in these cases.  You can also use various techniques provided by Solr for indexing and searching, such as EdgeNGramFilterFactory.  This is not a bug or an issue with the DemoSite.  Please see the Solr documentation for more information, and feel free to tune Solr to your needs.

**Comment by karopodgajecki** [comment]
@ktisdell I tried to add sortMissingLast="true" in schema.xml but this still don't work. That's why I have added this here. Am I doing something wrong ? Schema.xml looks like this:

http://pastebin.com/s8iCJAwU

**Comment by ktisdell** [comment]
I don't believe the sortMissingLast attribute has any impact on your the answer to your question. The field that you added the attribute to was the "namespace" field.  This should never be missing, with BLC out of the box.  So, this attribute should have no impact, given your original question.  Instead, you asked about searching for "sauc" vs. "sauce".  As I mentioned, adding a wildcard to the query (e.g. "sauc*") should work.  Or, you can use additional filters during indexing and querying, such as EdgeNGramFilterFactory.

**Comment by karopodgajecki** [comment]
Tried wildcard too:

```
    <fieldType name="text_general" class="solr.TextField" positionIncrementGap="100">
        <analyzer type="index">
            <tokenizer class="solr.KeywordTokenizerFactory"/>
            <filter class="solr.ASCIIFoldingFilterFactory"/>
            <filter class="solr.LowerCaseFilterFactory" />
            <filter class="solr.ReversedWildcardFilterFactory" />
        </analyzer>
        <analyzer type="query">
            <tokenizer class="solr.KeywordTokenizerFactory"/>
            <filter class="solr.ASCIIFoldingFilterFactory"/>
            <filter class="solr.LowerCaseFilterFactory" />
        </analyzer>
    </fieldType>
```

Don't give any results for souc

**Comment by ktisdell** [comment]
@spec8320 This is not a bug.  To get help with this issue. Please post your question in the forums: http://forum.broadleafcommerce.org/
