### ISSUE TITLE
images not showing on demosite

### ISSUE THREAD

**Issue by igorfodor** [BroadleafCommerce/LegacyDemoSite#81]
version: Broadleaf 3.1.0-GA

the thrown excpetion:
java.io.IOException: Failed to delete original file 'C:\apache-tomcat-7.0.37\temp\ba\5\Armageddon-The-Hot-Sauce-To-End-All-Bottle---d41d8cd98f00b204e9800998ecf8427e.jpg' after copy to 'C:\apache-tomcat-7.0.37\temp\img\sauces\Armageddon-The-Hot-Sauce-To-End-All-Bottle---d41d8cd98f00b204e9800998ecf8427e.jpg'
    at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2388)

**Comment by DeanWade** [comment]
I've encountered the same problem, and I came up with solution like here:
http://forum.broadleafcommerce.org/viewtopic.php?f=15&t=2441

**Comment by prabhatkataria** [comment]
@DeanWade I am using 3.1-SNAPSHOT and facing the same problem. I referred to the link you have mentioned but I am unable to find the class "StaticAssetStorageServiceImpl". Can you give some more input about it?

**Comment by phillipuniverse** [comment]
Closing this here, this only impacts Windows. Discussion will continue on the referenced pull request in the framework, BroadleafCommerce/BroadleafCommerce#769.
