### ISSUE TITLE
 No bean named 'blRegisterCustomerValidator' is defined?

### ISSUE THREAD

**Issue by letshan** [BroadleafCommerce/LegacyDemoSite#82]
I am new to Spring and Broadleaf; starting from DemoSite I configured 'site' project and 'admin' to depend on 'core'; maven compiled all good. Try run site/build.xml to start jetty, I got " org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'registerController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'blRegisterCustomerValidator' is defined" (to get the result I wait quite a while for jetty to start the server),

I assumed this is because the spring injection failure on site/src/main/webapp/WEB-INF/applicationContext-servlet.xml, but I don't understand why: the bl-profile-web.jar is in the classpath just like bl-profile.jar, so the component scan command "context:component-scan base-package="org.broadleafcommerce.profile.web.controller" should be able to find RegisterCustomerValidator just like it found the BroadleafRegisterController.

I tried to comment the @Resource(name="blRegisterCustomerValidator") annotation, then I got “ No bean named 'blLoginService' is defined”; the LoginService is also in bl-profile-web.jar so I guess I just can't ignore this issue.

Anyone got some ideas?

Thanks a lot,

Han

**Comment by timbaer** [comment]
I'm struggeling with the same exception here. Any advise how to fix that is highly appreciated. 

Cheers,

Stefan

**Comment by phillipuniverse** [comment]
I am unable to reproduce this exception. What version of Broadleaf and the DemoSite are you using?

**Comment by ArloL** [comment]
I see the `No bean named 'blLoginService' is defined` when I move the custom controllers into a different package and change the component scan for custom controllers.

My steps are:
- Refactor de.evosec.controller to de.evosec.serviceshop.controller
- Change base-package from de.evosec.controller to de.evosec.serviceshop.controller

I am using broadleaf 3.1.1-GA and the demo site is based on DemoSite-3.1.0-GA-eclipse-workspace.zip
