### ISSUE TITLE
Maven install command unable load all jar files

### ISSUE THREAD

**Issue by kranthiboinpally** [BroadleafCommerce/LegacyDemoSite#83]
I am using java 1.6 and maven 3.0.5 when ever I run maven installing I am getting following error 
ecommerce ...... ...............SUCCESS [0.373s]
,[INFO] core .............................................. FAILURE [2.291s],
[INFO] admin..... SKIPPED
[INFO] site .............................................. SKIPPED

Help could be appreciated. Thanks in advance

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ecommerce
[INFO] core
[INFO] admin
[INFO] site
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building ecommerce 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ ecommerce-website ---
[INFO] Installing C:\Users\kranthi\git\DemoSite\pom.xml to C:\Users\kranthi.m2\repository\com\mycompany\ecommerce-website\1.0\ecommerce-website-1.0.pom
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building core 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ core ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 82 resources
[INFO] 
[INFO] --- jrebel-maven-plugin:1.1.3:generate (generate-rebel-xml) @ core ---
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ core ---
[INFO] Compiling 22 source files to C:\Users\kranthi\git\DemoSite\core\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ecommerce ......................................... SUCCESS [0.373s]
[INFO] core .............................................. FAILURE [2.291s]
[INFO] admin ............................................. SKIPPED
[INFO] site .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.976s
[INFO] Finished at: Sun Feb 16 04:32:38 EST 2014
[INFO] Final Memory: 10M/90M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project core: Compilation failure: Compilation failure:
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\solr\solr-solrj\4.4.0\solr-solrj-4.4.0.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\zookeeper\zookeeper\3.4.5\zookeeper-3.4.5.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\httpcomponents\httpclient\4.2.3\httpclient-4.2.3.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\solr\solr-core\4.4.0\solr-core-4.4.0.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\lucene\lucene-core\4.4.0\lucene-core-4.4.0.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\lucene\lucene-analyzers-common\4.4.0\lucene-analyzers-common-4.4.0.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\lucene\lucene-analyzers-kuromoji\4.4.0\lucene-analyzers-kuromoji-4.4.0.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\lucene\lucene-queryparser\4.4.0\lucene-queryparser-4.4.0.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\hadoop\hadoop-common\2.0.5-alpha\hadoop-common-2.0.5-alpha.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\mortbay\jetty\jetty\6.1.26\jetty-6.1.26.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\commons-configuration\commons-configuration\1.6\commons-configuration-1.6.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\com\google\protobuf\protobuf-java\2.4.0a\protobuf-java-2.4.0a.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\hadoop\hadoop-hdfs\2.0.5-alpha\hadoop-hdfs-2.0.5-alpha.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\com\google\guava\guava\14.0.1\guava-14.0.1.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\mvel\mvel2\2.0.19\mvel2-2.0.19.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\hibernate\hibernate-tools\4.0.0-CR1\hibernate-tools-4.0.0-CR1.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\ant\ant\1.6.5\ant-1.6.5.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\freemarker\freemarker\2.3.8\freemarker-2.3.8.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\hibernate\jtidy\r8-20060801\jtidy-r8-20060801.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\eclipse\tycho\org.eclipse.jdt.core\3.8.0.v_C03\org.eclipse.jdt.core-3.8.0.v_C03.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\eclipse\text\3.2.0-v20060605-1400\text-3.2.0-v20060605-1400.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\springframework\security\spring-security-web\3.1.3.RELEASE\spring-security-web-3.1.3.RELEASE.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\log4j\log4j\1.2.12\log4j-1.2.12.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\springframework\spring-jms\3.2.2.RELEASE\spring-jms-3.2.2.RELEASE.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\springframework\spring-aop\3.2.2.RELEASE\spring-aop-3.2.2.RELEASE.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\springframework\spring-tx\3.2.2.RELEASE\spring-tx-3.2.2.RELEASE.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\velocity\velocity-tools\2.0\velocity-tools-2.0.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\commons-collections\commons-collections\3.2\commons-collections-3.2.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\struts\struts-core\1.3.8\struts-core-1.3.8.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\struts\struts-taglib\1.3.8\struts-taglib-1.3.8.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\apache\velocity\velocity\1.6.2\velocity-1.6.2.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\springframework\spring-web\3.2.2.RELEASE\spring-web-3.2.2.RELEASE.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\springframework\spring-webmvc\3.2.2.RELEASE\spring-webmvc-3.2.2.RELEASE.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\hibernate\javax\persistence\hibernate-jpa-2.0-api\1.0.0.Final\hibernate-jpa-2.0-api-1.0.0.Final.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\aspectj\aspectjweaver\1.6.5\aspectjweaver-1.6.5.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\springframework\security\spring-security-core\3.1.3.RELEASE\spring-security-core-3.1.3.RELEASE.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\springframework\spring-beans\3.2.2.RELEASE\spring-beans-3.2.2.RELEASE.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\springframework\spring-context\3.2.2.RELEASE\spring-context-3.2.2.RELEASE.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\springframework\spring-orm\3.2.2.RELEASE\spring-orm-3.2.2.RELEASE.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\org\springframework\spring-jdbc\3.2.2.RELEASE\spring-jdbc-3.2.2.RELEASE.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\net\sf\ehcache\ehcache\2.7.2\ehcache-2.7.2.jar; error in opening zip file
[ERROR] error: error reading C:\Users\kranthi.m2\repository\commons-beanutils\commons-beanutils\1.7.0\commons-beanutils-1.7.0.jar; error in opening zip file
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core

**Comment by jefffischer** [comment]
This is not a bug with the demo site installation, but is instead a problem with your environment. This type of issue is best addressed in our forum. Also, see here for some pointers on troubleshooting this type of problem: http://stackoverflow.com/questions/7600028/maven-error-in-opening-zip-file-when-running-maven

**Comment by messaoudi-mounir** [comment]
try mvn install -U
