### ISSUE TITLE
i18n Paypal supplied address checkout

### ISSUE THREAD

**Issue by watermelonjuice** [BroadleafCommerce/LegacyDemoSite#94]
Should the current states schema be changed to be more in line with ISO 3166-2 that Paypal uses?

For example:
Currently DemoSite has:
INSERT INTO BLC_STATE (NAME, ABBREVIATION, COUNTRY) VALUES ('ALABAMA','AL','US');
The ISO code for Alabama is US-AL.

**Comment by elbertbautista** [comment]
@watermelonjuice - Do you have an example of where PayPal actually sends back the ISO 3166-2 State codes? I know they use the IS0-3166-1 codes for Countries but for States, I've only seen them send back the following two characters specified here: https://developer.paypal.com/docs/classic/api/StateandProvinceCodes/

here is an example response:

``` text
TOKEN=EC-3V007823AV244874V&CHECKOUTSTATUS=PaymentActionNotInitiated&TIMESTAMP=2014-03-14T15:18:48Z&CORRELATIONID=49ee05cdc58e8&ACK=Success&VERSION=78.0&BUILD=10030158&EMAIL=test@broadleafcommerce.com&PAYERID=CTEZLURN5V47S&PAYERSTATUS=verified&FIRSTNAME=Test&LASTNAME=Test&COUNTRYCODE=US&SHIPTONAME=Bill Broadleaf&SHIPTOSTREET=123 Test Dr.&SHIPTOCITY=Austin&SHIPTOSTATE=TX&SHIPTOZIP=78759&SHIPTOCOUNTRYCODE=US&SHIPTOCOUNTRYNAME=United States&ADDRESSSTATUS=Confirmed&CURRENCYCODE=USD&AMT=10.00&ITEMAMT=10.00&SHIPPINGAMT=0.00&HANDLINGAMT=0.00&TAXAMT=0.00&CUSTOM=true_1394810269830&INSURANCEAMT=0.00&SHIPDISCAMT=0.00&L_NAME0=My Product Short Description&L_NUMBER0=1&L_QTY0=1&L_TAXAMT0=0.00&L_AMT0=10.00&L_DESC0=My Product Description&L_ITEMWEIGHTVALUE0=   0.00000&L_ITEMLENGTHVALUE0=   0.00000&L_ITEMWIDTHVALUE0=   0.00000&L_ITEMHEIGHTVALUE0=   0.00000&PAYMENTREQUEST_0_CURRENCYCODE=USD&PAYMENTREQUEST_0_AMT=10.00&PAYMENTREQUEST_0_ITEMAMT=10.00&PAYMENTREQUEST_0_SHIPPINGAMT=0.00&PAYMENTREQUEST_0_HANDLINGAMT=0.00&PAYMENTREQUEST_0_TAXAMT=0.00&PAYMENTREQUEST_0_CUSTOM=true_1394810269830&PAYMENTREQUEST_0_INSURANCEAMT=0.00&PAYMENTREQUEST_0_SHIPDISCAMT=0.00&PAYMENTREQUEST_0_SELLERPAYPALACCOUNTID=test@broadleafcommerce.com&PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED=false&PAYMENTREQUEST_0_SHIPTONAME=Bill Broadleaf&PAYMENTREQUEST_0_SHIPTOSTREET=123 Test Dr.&PAYMENTREQUEST_0_SHIPTOCITY=Austin&PAYMENTREQUEST_0_SHIPTOSTATE=TX&PAYMENTREQUEST_0_SHIPTOZIP=78759&PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE=US&PAYMENTREQUEST_0_SHIPTOCOUNTRYNAME=United States&PAYMENTREQUEST_0_ADDRESSSTATUS=Confirmed&L_PAYMENTREQUEST_0_NAME0=My Product Short Description&L_PAYMENTREQUEST_0_NUMBER0=1&L_PAYMENTREQUEST_0_QTY0=1&L_PAYMENTREQUEST_0_TAXAMT0=0.00&L_PAYMENTREQUEST_0_AMT0=10.00&L_PAYMENTREQUEST_0_DESC0=My Product Description&L_PAYMENTREQUEST_0_ITEMWEIGHTVALUE0=   0.00000&L_PAYMENTREQUEST_0_ITEMLENGTHVALUE0=   0.00000&L_PAYMENTREQUEST_0_ITEMWIDTHVALUE0=   0.00000&L_PAYMENTREQUEST_0_ITEMHEIGHTVALUE0=   0.00000&PAYMENTREQUESTINFO_0_ERRORCODE=0
```

**Comment by elbertbautista** [comment]
FYI, sent an email to PayPal Technical Support requesting a list of all international SHIPTOSTATE (PAYMENTREQUEST_0_SHIPTOSTATE) Values. They seem to be standardized per country from the requests we're testing with, however it isn't documented anywhere what that standard is publicly. So, waiting back on a response from their technical support. Hopefully they can help.

For example:
- France

```
PAYMENTREQUEST_0_SHIPTOSTREET=Av. de la Pelouse, 87648672 Mayet&PAYMENTREQUEST_0_SHIPTOCITY=Paris&PAYMENTREQUEST_0_SHIPTOSTATE=Alsace&PAYMENTREQUEST_0_SHIPTOZIP=75002&PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE=FR&PAYMENTREQUEST_0_SHIPTOCOUNTRYNAME=France
```
- Brasil

```
PAYMENTREQUEST_0_SHIPTOSTREET=1234 Rua Main&PAYMENTREQUEST_0_SHIPTOCITY=Rio De Janeiro&PAYMENTREQUEST_0_SHIPTOSTATE=RJ&PAYMENTREQUEST_0_SHIPTOZIP=22021-001&PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE=BR&PAYMENTREQUEST_0_SHIPTOCOUNTRYNAME=Brazil
```
- Australia

```
PAYMENTREQUEST_0_SHIPTOSTREET=1 Cheeseman AVE - East&PAYMENTREQUEST_0_SHIPTOCITY=Melbourne&PAYMENTREQUEST_0_SHIPTOSTATE=Victoria&PAYMENTREQUEST_0_SHIPTOZIP=3001&PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE=AU&PAYMENTREQUEST_0_SHIPTOCOUNTRYNAME=Australia
```
- China

```
PAYMENTREQUEST_0_SHIPTOSTREET=NO 1 Nan Jin Road&PAYMENTREQUEST_0_SHIPTOCITY=Shanghai&PAYMENTREQUEST_0_SHIPTOSTATE=Shanghai&PAYMENTREQUEST_0_SHIPTOZIP=200000&PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE=CN&PAYMENTREQUEST_0_SHIPTOCOUNTRYNAME=China
```

**Comment by elbertbautista** [comment]
We will revisit the model for i18N addresses in 3.2 that will be tracked with this ticket https://github.com/BroadleafCommerce/BroadleafCommerce/issues/775

For previous versions, you will need to either extend your Address entity to include a String field so as not to have a constraint to a State/Country or pre-seed your data with the possible values coming back from your integration. In PayPal's case, still waiting a response from them regarding non US and Canadian Province codes. Those can be found here: https://developer.paypal.com/docs/classic/api/StateandProvinceCodes/ as well as the Country codes here: https://developer.paypal.com/docs/classic/api/country_codes/

**Comment by phillipuniverse** [comment]
I'm going to go ahead and close this, looks like continued discussion is suited for BroadleafCommerce/BroadleafCommerce#775.

**Comment by elbertbautista** [comment]
Adding the official response back from PayPal Technical support:

> Thank you for contacting PayPal Merchant Technical Support.
> 
> Unfortunately we do not have a document that lists all parameters that can be returned in shiptostate. The ship to state syntax can vary because there are not the same sort of postal checks that go into US and Canadian states for all countries.

**Comment by phillipuniverse** [comment]
:+1: Paypal support

/s
