### ISSUE TITLE
compile time error in site project

### ISSUE THREAD

**Issue by sunil0791** [BroadleafCommerce/LegacyDemoSite#96]
getting error marker in https://github.com/BroadleafCommerce/DemoSite/blob/BroadleafCommerce-3.1.x/site/src/main/webapp/WEB-INF/applicationContext.xml for line number "11".
    <task:annotation-driven />

Is that required??. I don't see a need for it currently..

Thanks & Regards,
Sunil

**Comment by phillipuniverse** [comment]
It's not required, but it allows you to use the `@Async` annotations from Spring task: http://spring.io/blog/2010/01/05/task-scheduling-simplifications-in-spring-3-0/
